building the deploy-git-hook script
previous one didn't really do anything, so i cleaned it up and added some usage for help.  It works for my purposes...

  examples:

  1) to install all the hooks to foo git repo:

    deploy-git-hooks -d /path/to/foo -a

  2) to install only the pre-commit hook to bar git repo:

    deploy-git-hooks -d /path/to/bar -c

  3) to install only the pre-commit and pre-receive hook to foobar git repo:

    deploy-git-hooks -d /path/to/foobar -c -r

diff --git a/deploy-git-hook b/deploy-git-hook
--- a/deploy-git-hook
+++ b/deploy-git-hook
@@ -1,13 +1,98 @@
 #!/bin/bash
-#
 
-if [ -f .git ];
-then
-	LOCATION="$(awk '{print $2}' .git)"
-	LOCATION="$LOCATION/hooks/pre-commit"
-else
-	LOCATION=".git/hooks/pre-commit"
+usage() {
+  cat <<-EOF
+  usage: ${0} -d /path/to/git/repository [-a] [-c] [-r] [-u]
+
+    -h            this help screen
+    -d path       install the hooks to the specified path
+    -a            deploy pre-commit and pre-receive hooks
+    -c            deploy only the pre-commit hook
+    -r            deploy only the pre-receive hook
+    -u            deploy only the post-update hook
+
+  returns status code of 0 for success, otherwise, failure
+
+  examples:
+
+  1) to install pre-commit and pre-receive the hooks to foo git repo:
+
+    ${0} -d /path/to/foo -a
+
+  2) to install only the pre-commit hook to bar git repo:
+
+    ${0} -d /path/to/bar -c
+
+  3) to install only the pre-commit and pre-receive hook to foobar git repo:
+
+    ${0} -d /path/to/foobar -c -r
+
+EOF
+}
+
+while getopts ":d:achru" opt; do
+  case $opt in
+    a)
+      INST_COMMIT=1
+      INST_RECEIVE=1
+      ;;
+    c)
+      INST_COMMIT=1
+      ;;
+    d)
+      GIT_REPO="$OPTARG"
+      ;;
+    h)
+      usage
+      exit -1
+      ;;
+    r)
+      INST_RECEIVE=1
+      ;;
+    u)
+      INST_UPDATE=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      ;;
+  esac
+done
+
+if [[ -z "${INST_COMMIT}" \
+  && -z "${INST_RECEIVE}" \
+  && -z "${INST_UPDATE}" ]]; then
+  echo "Error: You must specify at least one hook to deploy" >&2
+  usage
+  exit -2
 fi
 
-#ln -s $HOME/Projecten/Github.com/puppet-git-hooks/pre-commit $LOCATION
-echo "pre-commit hook deployed to $LOCATION"
+if [ -z "${GIT_REPO}" ]; then
+  echo "Error: No repository specified" >&2
+  usage
+  exit -3
+elif [ ! -d "${GIT_REPO}/.git" ]; then
+  echo "Error: ${GIT_REPO} is not a valid git repository" >&2
+  exit -3
+fi
+
+HOOKS_DIR=$(dirname "${0}")
+HOOKS_DIR=$(cd "${HOOKS_DIR}" ; pwd)
+
+if [ "${INST_COMMIT}" = "1" ]; then
+  ln -sf "${HOOKS_DIR}/pre-commit" "${GIT_REPO}/.git/hooks/pre-commit" \
+  && echo "pre-commit hook deployed successfully" \
+  || ( echo "pre-commit hook failed to deploy" >&2 ; exit -4 )
+fi
+
+if [ "${INST_RECEIVE}" = "1" ]; then
+  ln -sf "${HOOKS_DIR}/pre-receive" "${GIT_REPO}/.git/hooks/pre-receive" \
+  && echo "pre-receive hook deployed successfully" \
+  || ( echo "pre-receive hook failed to deploy" >&2 ; exit -5 )
+fi
+
+if [ "${INST_UPDATE}" = "1" ]; then
+  ln -sf "${HOOKS_DIR}/post-update" "${GIT_REPO}/.git/hooks/post-update" \
+  && echo "post-update hook deployed successfully" \
+  || ( echo "post-update hook failed to deploy" >&2 ; exit -6 )
+fi
